### PR TITLE
I improved the README.md

### PR DESCRIPTION
**Pull request by NS007-dev**
@raineydavid I added on how to contribute. Please review. Thank you.

### CODE REVIEW

**Comment by NS007-dev** [comment]
@raineydavid , any updates? is there something wrong with my changes, that I should fix? or should I close this pr, thank you.

**Comment by raineydavid** [comment]
Lets discuss this. Technically p

**Comment by raineydavid** [comment]
Good commit, however not how we currently work so need to think about it. Currently we use Meetup.com/womencancode, however we are in the midst of reviewing the membership structure and want to better utilise Github Discussions.

**Comment by NS007-dev** [comment]
@raineydavid thank you

**Pull request closed without merging**
